# Generated by Django 2.2 on 2019-05-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20190505_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordergoods',
            name='goods_num',
            field=models.IntegerField(default=1, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='ordergoods',
            name='rate',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='评分'),
        ),
    ]
