# Generated by Django 2.2 on 2019-05-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20190506_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_num',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('success', '成功'), ('paying', '待支付'), ('cancel', '取消')], default='paying', max_length=30, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='trade_num',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='交易号'),
        ),
    ]
