# Generated by Django 2.2 on 2019-05-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20190509_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='freight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='运费'),
        ),
    ]
