# Generated by Django 2.2 on 2019-05-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190506_1736'),
        ('trade', '0011_auto_20190511_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('WAIT_BUYER_PAY', '交易创建'), ('TRADE_CLOSED', '超时关闭'), ('TRADE_SUCCESS', '支付成功'), ('TRADE_FINISHED', '交易结束')], default='WAIT_BUYER_PAY', max_length=30, verbose_name='交易状态'),
        ),
        migrations.AlterUniqueTogether(
            name='ordergoods',
            unique_together={('order', 'goods')},
        ),
    ]
