# Generated by Django 2.2 on 2019-05-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_auto_20190511_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordergoods',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='是否已评论'),
        ),
    ]
