# Generated by Django 2.2 on 2019-05-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_userprofile_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(help_text='用户头像', max_length=200, null=True, upload_to='users/avatar/', verbose_name='用户头像'),
        ),
    ]
