# Generated by Django 2.2 on 2019-05-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190504_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='area',
            field=models.CharField(help_text='收件区', max_length=10, verbose_name='收件区'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(help_text='收件城市', max_length=10, verbose_name='收件城市'),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(help_text='收件省份', max_length=10, verbose_name='收件省份'),
        ),
    ]
