# Generated by Django 2.2 on 2019-05-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190506_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
    ]
