# Generated by Django 2.2 on 2019-05-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20190430_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
